# Generated by Django 5.0.6 on 2026-09-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('BIENVENUE', 'Bienvenue / Enregistrement'), ('AFFECTATION', 'Affectation'), ('COURRIER', 'Courrier reçu'), ('DOCUMENT', 'Document reçu'), ('PUBLICATION', "Publication de l'église"), ('SYSTEME', 'Message système')], default='SYSTEME', max_length=20),
        ),
    ]
