# Generated by Django 5.0.6 on 2026-09-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0001_initial'),
        ('churches', '0003_eglise_responsable_email_eglise_responsable_nom_and_more'),
        ('notifications', '0002_alter_notification_type_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffusionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portee', models.CharField(choices=[('EGLISE', "Tous les membres d'une église"), ('DEPARTEMENT', "Membres d'un département"), ('BUREAU', "Membres d'un bureau"), ('NATIONAL', 'Tout le réseau')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nombre_destinataires', models.PositiveIntegerField(default=0)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffusions_notifications', to=settings.AUTH_USER_MODEL)),
                ('bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diffusions_notifications', to='bureaux.bureau')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diffusions_notifications', to='churches.departement')),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diffusions_notifications', to='churches.eglise')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
