import { useEffect, useState } from "react";
import client from "../api/client";

const initial = { nom:"", religion:"", region:"", prefecture:"", district:"", commune:"", adresse_precise:"", telephone:"", email:"", date_creation:"", responsable_nom:"", responsable_telephone:"", responsable_email:"", creer_compte_admin:true, admin_nom:"", admin_prenom:"", admin_telephone:"", admin_email:"", admin_mot_de_passe:"", admin_confirmation:"" };

export default function FormulaireEglise({ onFerme, onCree }) {
  const [religions, setReligions] = useState([]); const [regions, setRegions] = useState([]); const [prefectures, setPrefectures] = useState([]); const [districts, setDistricts] = useState([]); const [communes, setCommunes] = useState([]); const [erreur, setErreur] = useState(""); const [resultat, setResultat] = useState(null); const [form, setForm] = useState(initial);
  useEffect(() => { Promise.all([client.get("/religions/"), client.get("/geo/regions/")]).then(([r,g]) => {setReligions(r.data.results||r.data); setRegions(g.data.results||g.data);}); }, []);
  useEffect(() => { if (!form.region) {setPrefectures([]); return;} client.get("/geo/prefectures/",{params:{region:form.region}}).then(r=>setPrefectures(r.data.results||r.data)); },[form.region]);
  useEffect(() => { if (!form.prefecture) {setDistricts([]); return;} client.get("/geo/districts/",{params:{prefecture:form.prefecture}}).then(r=>setDistricts(r.data.results||r.data)); },[form.prefecture]);
  useEffect(() => { if (!form.district) {setCommunes([]); return;} client.get("/geo/communes/",{params:{district:form.district}}).then(r=>setCommunes(r.data.results||r.data)); },[form.district]);
  const m=(k,v)=>setForm(f=>({...f,[k]:v}));
  const normaliserNumero=(value)=>{
    const raw=String(value||"").trim().replace(/[\s().-]/g, "");
    if(raw.startsWith("00")) return "+"+raw.slice(2);
    if(raw.startsWith("+")) return "+"+raw.slice(1).replace(/\D/g, "");
    const digits=raw.replace(/\D/g, "");
    if(digits.length===9 && digits.startsWith("6")) return "+224"+digits;
    if(digits.startsWith("224") && digits.length===12) return "+"+digits;
    return raw;
  };
  const soumettre=async(e)=>{
    e.preventDefault();setErreur("");
    const payload={...form, plateforme_active:false, admin_telephone:normaliserNumero(form.admin_telephone), responsable_telephone:normaliserNumero(form.responsable_telephone), telephone:normaliserNumero(form.telephone)};
    try{
      const r=await client.post("/eglises/",payload);
      setResultat(r.data);
    }catch(err){
      const d=err.response?.data;
      const messages=Object.values(d||{}).flat().filter(Boolean);
      setErreur(typeof d==="string"?d:(d?.detail||messages.join(" ")||"Impossible de créer l'église."));
    }
  };
  if(resultat) return <div className="modale-fond"><div className="modale"><div className="success-box"><div className="success-icon">✓</div><h3>Église créée avec succès</h3><p>{resultat.nom} est maintenant enregistrée dans le réseau.</p><div className="credential-box"><small>Identifiant administrateur local</small><strong>{resultat.compte_admin?.identifiant || "Non créé"}</strong><small>{resultat.compte_admin?.actif ? "Compte actif" : "Compte en attente de confirmation SMS"}</small>{resultat.plateforme_active!==undefined&&<><small>Plateforme</small><strong>{resultat.plateforme_active?"ACTIVE":"À ACTIVER PLUS TARD"}</strong></>}{resultat.sms&&<><small>SMS</small><strong>{resultat.sms.statut||"—"}</strong>{resultat.sms.messages?.map((m,i)=>m.test_code?<small key={i}>Code de test : <b>{m.test_code}</b></small>:null)}</>}</div><button className="btn" onClick={()=>{onCree?.(resultat);onFerme();}}>Fermer</button></div></div></div>;
  return <div className="modale-fond" onClick={onFerme}><div className="modale xl" onClick={e=>e.stopPropagation()}><div className="section-header"><div><span className="eyebrow">ENREGISTREMENT NATIONAL</span><h3>Créer une nouvelle église</h3><p>Une église et son espace privé sont créés ensemble.</p></div></div><form onSubmit={soumettre}>
    <div className="form-section"><h4>Informations de l'église</h4><div className="form-grid"><div className="form-champ"><label>Nom *</label><input required value={form.nom} onChange={e=>m("nom",e.target.value)} /></div><div className="form-champ"><label>Religion *</label><select required value={form.religion} onChange={e=>m("religion",e.target.value)}><option value="">Choisir</option>{religions.map(r=><option key={r.id} value={r.id}>{r.nom}</option>)}</select></div><div className="form-champ"><label>Région *</label><select required value={form.region} onChange={e=>m("region",e.target.value)}><option value="">Choisir</option>{regions.map(r=><option key={r.id} value={r.id}>{r.nom}</option>)}</select></div><div className="form-champ"><label>Préfecture *</label><select required disabled={!form.region} value={form.prefecture} onChange={e=>m("prefecture",e.target.value)}><option value="">Choisir</option>{prefectures.map(r=><option key={r.id} value={r.id}>{r.nom}</option>)}</select></div><div className="form-champ"><label>District *</label><select required disabled={!form.prefecture} value={form.district} onChange={e=>m("district",e.target.value)}><option value="">Choisir</option>{districts.map(r=><option key={r.id} value={r.id}>{r.nom}</option>)}</select></div><div className="form-champ"><label>Commune</label><select disabled={!form.district} value={form.commune} onChange={e=>m("commune",e.target.value)}><option value="">Choisir</option>{communes.map(r=><option key={r.id} value={r.id}>{r.nom}</option>)}</select></div><div className="form-champ"><label>Téléphone</label><input value={form.telephone} onChange={e=>m("telephone",e.target.value)} /></div><div className="form-champ"><label>Email</label><input type="email" value={form.email} onChange={e=>m("email",e.target.value)} /></div></div><div className="form-champ"><label>Adresse précise</label><input value={form.adresse_precise} onChange={e=>m("adresse_precise",e.target.value)} /></div><div className="form-champ"><label>Date de fondation *</label><input required type="date" value={form.date_creation} onChange={e=>m("date_creation",e.target.value)} /></div></div>
    <div className="form-section admin-section"><h4>Responsable de l’église</h4><p className="sous-titre">Le responsable peut déjà posséder un compte EESAG ou être saisi maintenant. Il n'est pas obligatoire de choisir un administrateur existant.</p><div className="form-grid"><div className="form-champ"><label>Nom du responsable *</label><input required value={form.responsable_nom} onChange={e=>m("responsable_nom",e.target.value)} placeholder="Ex. Pasteur Jean Dupont" /></div><div className="form-champ"><label>Téléphone <small>(ex. +224626483701)</small></label><input inputMode="tel" value={form.responsable_telephone} onChange={e=>m("responsable_telephone",e.target.value)} placeholder="+224..." /></div><div className="form-champ"><label>Email</label><input type="email" value={form.responsable_email} onChange={e=>m("responsable_email",e.target.value)} /></div></div></div>
    <div className="form-section admin-section"><div className="activation-note"><b>Accès à la plateforme</b><small>La nouvelle église est créée désactivée. Son activation est volontairement réservée au Bureau national dans l’administration Django.</small></div><label className="checkbox-line"><input type="checkbox" checked={form.creer_compte_admin} onChange={e=>m("creer_compte_admin",e.target.checked)} /><span><b>Créer le compte administrateur local maintenant</b><small>L'administrateur pourra ensuite gérer uniquement cette église.</small></span></label>{form.creer_compte_admin&&<div className="form-grid"><div className="form-champ"><label>Nom *</label><input required value={form.admin_nom} onChange={e=>m("admin_nom",e.target.value)} /></div><div className="form-champ"><label>Prénom *</label><input required value={form.admin_prenom} onChange={e=>m("admin_prenom",e.target.value)} /></div><div className="form-champ"><label>Téléphone * <small>(ex. +224626483701)</small></label><input required inputMode="tel" value={form.admin_telephone} onChange={e=>m("admin_telephone",e.target.value)} /></div><div className="form-champ"><label>Email</label><input type="email" value={form.admin_email} onChange={e=>m("admin_email",e.target.value)} /></div><div className="form-champ"><label>Mot de passe *</label><input required minLength="6" type="password" value={form.admin_mot_de_passe} onChange={e=>m("admin_mot_de_passe",e.target.value)} /></div><div className="form-champ"><label>Confirmation *</label><input required minLength="6" type="password" value={form.admin_confirmation} onChange={e=>m("admin_confirmation",e.target.value)} /></div></div>}</div>
    {erreur&&<p className="erreur">{erreur}</p>}<div className="modal-actions"><button className="btn" type="submit">Créer l'église et son espace</button><button className="btn btn-secondaire" type="button" onClick={onFerme}>Annuler</button></div>
  </form></div></div>;
}
