import { useEffect, useState } from "react";
import client from "../api/client";
import { useAuth } from "../context/AuthContext";

export default function Notifications() {
  const { peutGerer, estNational, utilisateur } = useAuth();
  const [notifications,setNotifications]=useState([]); const [eglises,setEglises]=useState([]); const [afficher,setAfficher]=useState(false);
  const [form,setForm]=useState({titre:"",message:"",eglise:""}); const [erreur,setErreur]=useState("");
  const charger=()=>client.get("/notifications/").then(r=>setNotifications(r.data.results||r.data));
  useEffect(()=>{charger(); if(estNational) client.get("/eglises/").then(r=>setEglises(r.data.results||r.data));},[estNational]);
  const marquer=async(id)=>{await client.post(`/notifications/${id}/marquer_lu/`);charger();};
  const tout=async()=>{await client.post("/notifications/tout_marquer_lu/");charger();};
  const envoyer=async(e)=>{e.preventDefault();setErreur("");try{await client.post("/notifications/envoyer/",{...form,eglise:estNational?form.eglise:utilisateur?.eglise});setAfficher(false);setForm({titre:"",message:"",eglise:""});}catch(err){setErreur(err.response?.data?.detail||"Impossible d'envoyer la notification.");}};
  return <div><div className="barre-superieure"><div><h2>Centre de notifications</h2><p className="sous-titre">Vos messages privés, alertes et communications officielles.</p></div><div className="actions">{peutGerer&&<button className="btn" onClick={()=>setAfficher(true)}>＋ Envoyer une notification</button>}<button className="btn btn-secondaire" onClick={tout}>Tout marquer lu</button></div></div>{notifications.map(n=><article key={n.id} className={`notif-card ${!n.lu?"unread":""}`} onClick={()=>!n.lu&&marquer(n.id)}><div className="notif-type">{n.type_notification}</div><div className="notif-content"><b>{n.titre}</b><p>{n.message}</p><small>{new Date(n.date_creation).toLocaleString("fr-FR")}</small></div><span className={`dot ${n.lu?"off":""}`}></span></article>)}{!notifications.length&&<div className="carte empty-state">Aucune notification pour le moment.</div>}{afficher&&<div className="modale-fond" onClick={()=>setAfficher(false)}><div className="modale" onClick={e=>e.stopPropagation()}><h3>Envoyer une notification</h3><p className="sous-titre">{estNational?"Choisissez l'église qui recevra le message.":"Tous les membres actifs de votre église la recevront."}</p><form onSubmit={envoyer}>{estNational&&<div className="form-champ"><label>Église destinataire *</label><select required value={form.eglise} onChange={e=>setForm({...form,eglise:e.target.value})}><option value="">Choisir une église</option>{eglises.map(e=><option key={e.id} value={e.id}>{e.nom} ({e.code})</option>)}</select></div>}<div className="form-champ"><label>Titre *</label><input required value={form.titre} onChange={e=>setForm({...form,titre:e.target.value})}/></div><div className="form-champ"><label>Message *</label><textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></div>{erreur&&<p className="erreur">{erreur}</p>}<div className="modal-actions"><button className="btn">Envoyer</button><button type="button" className="btn btn-secondaire" onClick={()=>setAfficher(false)}>Annuler</button></div></form></div></div>}</div>;
}
