import { useEffect, useState } from "react";
import client from "../api/client";
import { useAuth } from "../context/AuthContext";

const empty = { titre:"", description:"", plateforme:"JITSI", lien:"", date_debut:"", date_fin:"", eglise:"" };
export default function Reunions(){
  const { utilisateur, estNational, peutGerer } = useAuth();
  const [reunions,setReunions]=useState([]); const [eglises,setEglises]=useState([]); const [form,setForm]=useState({...empty}); const [open,setOpen]=useState(false); const [error,setError]=useState("");
  const charger=()=>client.get("/reunions/").then(r=>setReunions(r.data.results||r.data)).catch(()=>setError("Impossible de charger les réunions."));
  useEffect(()=>{charger(); if(estNational) client.get("/eglises/").then(r=>setEglises(r.data.results||r.data)).catch(()=>{});},[estNational]);
  const creer=async e=>{e.preventDefault();setError(""); try{await client.post("/reunions/",{...form,eglise:estNational?(form.eglise||null):utilisateur?.eglise}); setForm({...empty});setOpen(false);charger();}catch(err){setError(err.response?.data?.detail||"La réunion n'a pas pu être créée.");}};
  return <div className="meetings-page"><div className="page-hero meetings-hero"><div><span className="eyebrow">RÉUNIONS • VISIOCONFÉRENCE</span><h1>Réunions EESAG</h1><p>Planifiez et rejoignez les réunions nationales ou celles de votre église.</p></div>{peutGerer&&<button className="btn" onClick={()=>setOpen(true)}>+ Nouvelle réunion</button>}</div>{error&&<div className="console-error">{error}</div>}<div className="meeting-grid">{reunions.map(r=><article className="carte meeting-card" key={r.id}><div className="meeting-card-head"><span className="panel-chip">{r.plateforme}</span><span>{new Date(r.date_debut).toLocaleString("fr-FR")}</span></div><h3>{r.titre}</h3><p>{r.description||"Réunion EESAG"}</p><small>{r.eglise_nom||"Bureau national"}</small><a className="btn" href={r.lien} target="_blank" rel="noreferrer">Rejoindre la visioconférence ↗</a></article>)}{!reunions.length&&<div className="empty-state">Aucune réunion programmée.</div>}</div>{open&&<div className="modale-fond" onClick={()=>setOpen(false)}><form className="modale" onSubmit={creer} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">NOUVELLE RÉUNION</span><h3>Planifier une visioconférence</h3></div><button className="modal-close" type="button" onClick={()=>setOpen(false)}>×</button></div><div className="form-champ"><label>Titre *</label><input required value={form.titre} onChange={e=>setForm({...form,titre:e.target.value})}/></div><div className="form-champ"><label>Description</label><textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>{estNational&&<div className="form-champ"><label>Église / périmètre</label><select value={form.eglise} onChange={e=>setForm({...form,eglise:e.target.value})}><option value="">Bureau national</option>{eglises.map(x=><option value={x.id} key={x.id}>{x.nom}</option>)}</select></div>}<div className="form-row"><div className="form-champ"><label>Plateforme</label><select value={form.plateforme} onChange={e=>setForm({...form,plateforme:e.target.value})}><option value="JITSI">Jitsi Meet</option><option value="ZOOM">Zoom</option><option value="MEET">Google Meet</option><option value="AUTRE">Autre</option></select></div><div className="form-champ"><label>Date / heure *</label><input required type="datetime-local" value={form.date_debut} onChange={e=>setForm({...form,date_debut:e.target.value})}/></div></div><div className="form-champ"><label>Lien de visioconférence *</label><input required type="url" placeholder="https://meet.jit.si/..." value={form.lien} onChange={e=>setForm({...form,lien:e.target.value})}/></div><div className="modal-actions"><button className="btn btn-secondaire" type="button" onClick={()=>setOpen(false)}>Annuler</button><button className="btn">Créer la réunion</button></div></form></div>}</div>
}
