# Generated by Django 5.0.6 on 2026-09-16 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bureaux', '0002_bureaumembre'),
        ('churches', '0005_eglise_activee_par_eglise_date_activation_plateforme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionnaliteSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('nom', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('groupe', models.CharField(default='Général', max_length=80)),
                ('actif_global', models.BooleanField(default=True)),
                ('reservable', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fonctionnalité système',
                'verbose_name_plural': 'Fonctionnalités système',
                'ordering': ['groupe', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilDeveloppeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('titre', models.CharField(blank=True, max_length=180)),
                ('biographie', models.TextField(blank=True)),
                ('parcours', models.TextField(blank=True)),
                ('experiences', models.TextField(blank=True)),
                ('competences', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='developpeur/')),
                ('email_public', models.EmailField(blank=True, max_length=254)),
                ('lien_public', models.URLField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationMonetisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False)),
                ('devise', models.CharField(default='GNF', max_length=10)),
                ('fournisseur', models.CharField(blank=True, max_length=80)),
                ('compte_destination', models.CharField(blank=True, max_length=180)),
                ('url_paiement', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_monetisation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('NOUVEAUTE', 'Nouvelle fonctionnalité'), ('MAINTENANCE', 'Maintenance'), ('URGENT', 'Urgent')], default='INFO', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('publie_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_creees', to=settings.AUTH_USER_MODEL)),
                ('fonctionnalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='core.fonctionnalitesysteme')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActivationFonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_activation', models.DateTimeField(auto_now=True)),
                ('active_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activations_fonctionnalites', to=settings.AUTH_USER_MODEL)),
                ('bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctionnalites_activees', to='bureaux.bureau')),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctionnalites_activees', to='churches.eglise')),
                ('fonctionnalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.fonctionnalitesysteme')),
            ],
        ),
        migrations.CreateModel(
            name='OffreMiseAJourSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('titre', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('devise', models.CharField(default='GNF', max_length=10)),
                ('gratuite', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('publie_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_mise_a_jour_creees', to=settings.AUTH_USER_MODEL)),
                ('fonctionnalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_mise_a_jour', to='core.fonctionnalitesysteme')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='activationfonctionnalite',
            constraint=models.UniqueConstraint(condition=models.Q(('bureau__isnull', True), ('eglise__isnull', False)), fields=('fonctionnalite', 'eglise'), name='uniq_feature_eglise'),
        ),
        migrations.AddConstraint(
            model_name='activationfonctionnalite',
            constraint=models.UniqueConstraint(condition=models.Q(('bureau__isnull', False), ('eglise__isnull', True)), fields=('fonctionnalite', 'bureau'), name='uniq_feature_bureau'),
        ),
    ]
