# Generated by Django 5.0.6 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('adresse_precise', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateField(help_text="Date de création/fondation de l'église")),
                ('date_enregistrement_systeme', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('FERMEE', 'Fermée')], default='ACTIVE', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_eglises/')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eglises', to='geo.commune')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eglises', to='geo.district')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eglises', to='geo.prefecture')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eglises', to='geo.region')),
                ('responsable', models.ForeignKey(blank=True, help_text='Pasteur / responsable actuellement affecté à cette église.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eglises_dont_il_est_responsable', to=settings.AUTH_USER_MODEL)),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eglises', to='churches.religion')),
            ],
            options={
                'verbose_name': 'Église',
                'verbose_name_plural': 'Églises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='churches.eglise')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('nom', 'eglise')},
            },
        ),
    ]
