# Generated by Django 5.0.6 on 2026-09-12 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexes', to='churches.eglise')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annexes_dirigees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annexe',
                'verbose_name_plural': 'Annexes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='annexe',
            constraint=models.UniqueConstraint(fields=('eglise', 'nom'), name='unique_annexe_nom_par_eglise'),
        ),
    ]
