# Generated by Django 5.0.6 on 2026-09-12 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_annexe_annexe_unique_annexe_nom_par_eglise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='responsable_email',
            field=models.EmailField(blank=True, help_text='Email du responsable (facultatif).', max_length=254),
        ),
        migrations.AddField(
            model_name='eglise',
            name='responsable_nom',
            field=models.CharField(blank=True, help_text="Nom du responsable si cette personne n'a pas encore de compte EESAG.", max_length=200),
        ),
        migrations.AddField(
            model_name='eglise',
            name='responsable_telephone',
            field=models.CharField(blank=True, help_text='Téléphone du responsable (facultatif).', max_length=20),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Responsable déjà enregistré dans EESAG (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eglises_dont_il_est_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
