# Generated by Django 5.0.6 on 2026-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_eglise_responsable_email_eglise_responsable_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleEglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Rôle dans l'église",
                'verbose_name_plural': "Rôles dans l'église",
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='departement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='eglise',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='responsable',
        ),
    ]
