# Generated by Django 5.0.6 on 2026-09-16 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_roleeglise_alter_departement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='activee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eglises_activees_plateforme', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eglise',
            name='date_activation_plateforme',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eglise',
            name='plateforme_active',
            field=models.BooleanField(default=True, help_text="Autorise l'accès à la plateforme pour cette église."),
        ),
    ]
