# Generated by Django 5.0.6 on 2026-09-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0005_eglise_activee_par_eglise_date_activation_plateforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eglise',
            name='plateforme_active',
            field=models.BooleanField(default=False, help_text='Accès activé uniquement par le Bureau national.'),
        ),
    ]
