# Generated by Django 5.0.6 on 2026-09-12 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_annexe_annexe_unique_annexe_nom_par_eglise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ANALYSE', 'Analyse'), ('BROUILLON', 'Brouillon'), ('MISE_A_JOUR', 'Suggestions de mise à jour'), ('RAPPORT', 'Synthèse de rapport')], max_length=20)),
                ('entree', models.TextField(blank=True)),
                ('resultat', models.TextField(blank=True)),
                ('fournisseur', models.CharField(default='local', max_length=40)),
                ('succes', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_ia', to='churches.eglise')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal IA',
                'verbose_name_plural': 'Journaux IA',
                'ordering': ['-cree_le'],
            },
        ),
    ]
