# Generated by Django 5.0.6 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_utilise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='PLANIFIE', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('eglise', models.ForeignKey(blank=True, help_text='Vide = projet national.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='churches.eglise')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('DIME', 'Dîme'), ('OFFRANDE', 'Offrande'), ('DON', 'Don'), ('AUTRE_ENTREE', 'Autre entrée'), ('SORTIE', 'Sortie / Dépense')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(default='GNF', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_transaction', models.DateField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('eglise', models.ForeignKey(blank=True, help_text='Vide = transaction du Bureau National.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='churches.eglise')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_transaction'],
            },
        ),
    ]
