# Generated by Django 5.0.6 on 2026-09-14 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0001_initial'),
        ('churches', '0003_eglise_responsable_email_eglise_responsable_nom_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='annee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='bureau',
            field=models.ForeignKey(blank=True, help_text='Projet porté par un bureau national ou local.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='bureaux.bureau'),
        ),
        migrations.AddField(
            model_name='projet',
            name='objectif',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='type_projet',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bureau',
            field=models.ForeignKey(blank=True, help_text='Transaction d’un bureau national ou local. Laisser vide pour le socle financier national historique.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bureaux.bureau'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='eglise',
            field=models.ForeignKey(blank=True, help_text='Projet porté directement par une église.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='churches.eglise'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='eglise',
            field=models.ForeignKey(blank=True, help_text='Transaction de cette église locale.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='churches.eglise'),
        ),
    ]
