# Generated by Django 5.0.6 on 2026-09-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('identifiant', models.CharField(editable=False, max_length=20, unique=True)),
                ('code_secret_clair', models.CharField(blank=True, help_text="Conservé UNE fois en clair pour l'envoi SMS initial (à ne pas afficher ensuite).", max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_utilisateurs/')),
                ('role', models.CharField(choices=[('COORDINATEUR', 'Coordinateur du système'), ('SUPERADMIN_INTL', 'Super Administrateur International'), ('SUPERADMIN_NATIONAL', 'Super Administrateur National'), ('ADMIN_LOCAL', 'Administrateur Local (église)'), ('PASTEUR', 'Pasteur'), ('RESPONSABLE_DEPARTEMENT', 'Responsable de département'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=30)),
                ('fonction_bureau_national', models.CharField(blank=True, help_text='Ex: Président, Secrétaire Général... (si membre du bureau national)', max_length=150)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
