# Generated by Django 5.0.6 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_departement', to='churches.departement'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='eglise',
            field=models.ForeignKey(blank=True, help_text='Église de rattachement (vide pour les rôles nationaux).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='churches.eglise'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='eglise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='churches.eglise'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='abonnement',
            unique_together={('utilisateur', 'eglise')},
        ),
    ]
