# Generated by Django 5.0.6 on 2026-09-12 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionEglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('libelle', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_bapteme_eau',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_bapteme_saint_esprit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fonction_eglise',
            field=models.CharField(blank=True, choices=[('MEMBRE', 'Membre'), ('PASTEUR', 'Pasteur'), ('PASTEUR_ASSISTANT', 'Pasteur assistant'), ('DIACRE', 'Diacre'), ('ANCIEN', 'Ancien'), ('RESPONSABLE_DEPARTEMENT', 'Responsable de département'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier'), ('CHANTRE', 'Chantre'), ('MONITEUR', 'Moniteur / Monitrice'), ('MISSIONNAIRE', 'Missionnaire'), ('AUTRE', 'Autre')], default='MEMBRE', max_length=40),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nationalite',
            field=models.CharField(choices=[('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('CI', 'Côte d’Ivoire'), ('LR', 'Libéria'), ('SL', 'Sierra Leone'), ('GH', 'Ghana'), ('NG', 'Nigéria'), ('BF', 'Burkina Faso'), ('FR', 'France'), ('US', 'États-Unis'), ('CA', 'Canada'), ('OTHER', 'Autre')], default='GN', max_length=20),
        ),
        migrations.CreateModel(
            name='MandatBureauNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('poste', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('date_nomination', models.DateField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats_bureau_national', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mandat du Bureau national',
                'verbose_name_plural': 'Mandats du Bureau national',
                'ordering': ['-annee', 'poste'],
            },
        ),
        migrations.CreateModel(
            name='DelegationEglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_creees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_eglise', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='delegations', to='accounts.permissioneglise')),
            ],
            options={
                'verbose_name': 'Délégation de droits',
                'verbose_name_plural': 'Délégations de droits',
            },
        ),
        migrations.CreateModel(
            name='VerificationTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_telephone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='mandatbureaunational',
            constraint=models.UniqueConstraint(fields=('annee', 'utilisateur'), name='unique_mandat_utilisateur_annee'),
        ),
    ]
