# Generated by Django 5.0.6 on 2026-09-12 16:29

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permissioneglise_utilisateur_date_bapteme_eau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_utilisateurs/', validators=[apps.accounts.models.valider_taille_photo]),
        ),
    ]
