# Generated by Django 5.0.6 on 2026-09-12 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('COORDINATEUR', 'Coordinateur du système'), ('SUPERADMIN_INTL', 'Bureau national (hérité)'), ('SUPERADMIN_NATIONAL', 'Administrateur du Bureau national'), ('ADMIN_LOCAL', 'Administrateur Local (église)'), ('PASTEUR', 'Pasteur'), ('RESPONSABLE_DEPARTEMENT', 'Responsable de département'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=30),
        ),
        migrations.CreateModel(
            name='JournalSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=30)),
                ('type_message', models.CharField(default='INFORMATION', max_length=40)),
                ('fournisseur', models.CharField(default='console', max_length=30)),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('SIMULE', 'Simulé')], default='SIMULE', max_length=20)),
                ('message', models.TextField()),
                ('provider_sid', models.CharField(blank=True, max_length=80)),
                ('erreur', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_sms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal SMS',
                'verbose_name_plural': 'Journal SMS',
                'ordering': ['-cree_le'],
            },
        ),
    ]
