# Generated by Django 5.0.6 on 2026-09-14 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_utilisateur_role_journalsms'),
        ('churches', '0004_roleeglise_alter_departement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role_eglise',
            field=models.ForeignKey(blank=True, help_text='Rôle/fonction du membre dans son église, distinct du rôle technique du compte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='churches.roleeglise'),
        ),
    ]
