# Generated by Django 5.0.6 on 2026-09-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0003_eglise_responsable_email_eglise_responsable_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                ('code', models.CharField(editable=False, max_length=40, unique=True)),
                ('niveau', models.CharField(choices=[('NATIONAL', 'Bureau national'), ('LOCAL', "Bureau d'église")], default='NATIONAL', max_length=20)),
                ('type_bureau', models.CharField(choices=[('FEMMES', 'Bureau national des femmes'), ('JEUNESSE', 'Bureau national de la jeunesse'), ('ENFANTS', 'Bureau national des enfants'), ('EVANGELISATION', "Équipe nationale d'évangélisation"), ('HOMMES', 'Bureau national des hommes'), ('FAMILLES', 'Bureau national des familles'), ('COMMUNICATION', 'Bureau de la communication'), ('MUSIQUE', 'Bureau de la musique / chorale'), ('MISSIONS', 'Bureau des missions'), ('AUTRE', 'Autre bureau / commission')], default='AUTRE', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='churches.eglise')),
            ],
            options={
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='BureauAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_gerer_membres', models.BooleanField(default=True)),
                ('peut_gerer_finances', models.BooleanField(default=False)),
                ('peut_gerer_projets', models.BooleanField(default=True)),
                ('peut_envoyer_notifications', models.BooleanField(default=True)),
                ('peut_gerer_rapports', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrateurs', to='bureaux.bureau')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux_administres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bureau__nom', 'utilisateur__nom', 'utilisateur__prenom'],
            },
        ),
        migrations.CreateModel(
            name='BureauMembreMandat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('poste', models.CharField(max_length=160)),
                ('objectif_annuel', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_nomination', models.DateTimeField(auto_now_add=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats', to='bureaux.bureau')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats_bureaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-annee', 'bureau__nom', 'poste'],
            },
        ),
        migrations.AddConstraint(
            model_name='bureau',
            constraint=models.UniqueConstraint(fields=('niveau', 'type_bureau', 'eglise'), name='uniq_bureau_type_niveau_eglise'),
        ),
        migrations.AddConstraint(
            model_name='bureauadministrateur',
            constraint=models.UniqueConstraint(fields=('bureau', 'utilisateur'), name='uniq_admin_bureau_utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='bureaumembremandat',
            constraint=models.UniqueConstraint(fields=('bureau', 'utilisateur', 'annee'), name='uniq_mandat_bureau_utilisateur_annee'),
        ),
    ]
