# Generated by Django 5.0.6 on 2026-09-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=180)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bureaux/membres/')),
                ('poste', models.CharField(max_length=160)),
                ('annee', models.PositiveIntegerField(default=2026)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_independants', to='bureaux.bureau')),
            ],
            options={
                'ordering': ['ordre', 'nom_complet'],
                'indexes': [models.Index(fields=['bureau', 'annee', 'actif'], name='bureaux_bur_bureau__f18ebc_idx'), models.Index(fields=['nom_complet'], name='bureaux_bur_nom_com_cc4439_idx')],
            },
        ),
    ]
