import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Connexion() {
  const [identifiant,setIdentifiant]=useState(""); const [password,setPassword]=useState(""); const [erreur,setErreur]=useState(""); const [enCours,setEnCours]=useState(false); const {connecter}=useAuth(); const navigate=useNavigate();
  const soumettre=async(e)=>{e.preventDefault();setErreur("");setEnCours(true);try{const user=await connecter(identifiant.trim(),password);navigate(user?.role?.includes("SUPERADMIN")||user?.role==="COORDINATEUR"?"/national":"/");}catch(err){setErreur(err.response?.data?.detail||"Identifiant ou code secret incorrect.");}finally{setEnCours(false);}};
  return <div className="page-connexion"><section className="connexion-brand"><div><span className="eyebrow">PORTAIL SÉCURISÉ</span><h1>Un réseau d'églises.<br/>Un espace pour chacune.</h1><p>La plateforme centralise la coordination nationale tout en conservant les membres, projets, annexes, documents et communications de chaque église dans un espace privé.</p></div></section><section className="boite-connexion"><span className="eyebrow">CONNEXION</span><h1>Accéder à mon espace</h1><p className="sous-titre">Utilisez votre identifiant personnel et votre code secret.</p><form onSubmit={soumettre}><div className="form-champ"><label>Identifiant</label><input autoComplete="username" value={identifiant} onChange={e=>setIdentifiant(e.target.value)} placeholder="EGL12345-000001" required /></div><div className="form-champ"><label>Code secret</label><input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></div>{erreur&&<p className="erreur">{erreur}</p>}<button className="btn" disabled={enCours}>{enCours?"Connexion…":"Se connecter"}</button><button type="button" className="btn btn-secondaire" onClick={()=>navigate("/inscription")}>Créer mon compte membre</button></form></section></div>;
}
