import {useState} from "react";
import {useNavigate} from "react-router-dom";
import client from "../api/client";

export default function Inscription(){
  const [f,setF]=useState({nom:"",prenom:"",telephone:"",email:"",code_eglise:"",password:"",password_confirmation:""});
  const [otp,setOtp]=useState(""); const [identifiant,setIdentifiant]=useState(""); const [testCode,setTestCode]=useState("");
  const [testMode,setTestMode]=useState(false); const [etape,setEtape]=useState(1); const [erreur,setErreur]=useState("");
  const nav=useNavigate(); const change=e=>setF({...f,[e.target.name]:e.target.value});
  const creer=async e=>{e.preventDefault();setErreur("");try{const r=await client.post("/auth/inscription/",f);setIdentifiant(r.data.identifiant);setTestMode(Boolean(r.data.test_mode));setTestCode(r.data.test_code||"");setEtape(2);}catch(err){setErreur(err.response?.data?.detail||Object.values(err.response?.data||{}).flat().join(" ")||"Impossible de créer le compte.");}};
  const confirmer=async e=>{e.preventDefault();setErreur("");try{await client.post("/auth/verification-telephone/",{identifiant,code:otp});nav("/connexion");}catch(err){setErreur(err.response?.data?.detail||Object.values(err.response?.data||{}).flat().join(" ")||"Code invalide.");}};
  return <div className="page-connexion"><section className="connexion-brand"><div><span className="eyebrow">NOUVEAU MEMBRE</span><h1>Créer mon compte personnel.</h1><p>Créez votre compte, confirmez votre numéro puis accédez à votre espace EESAG.</p></div></section><section className="boite-connexion"><span className="eyebrow">{etape===1?"INSCRIPTION":"VÉRIFICATION DU NUMÉRO"}</span>{etape===1?<form onSubmit={creer}><div className="form-grid"><div className="form-champ"><label>Nom</label><input name="nom" value={f.nom} onChange={change} required/></div><div className="form-champ"><label>Prénom</label><input name="prenom" value={f.prenom} onChange={change} required/></div></div><div className="form-champ"><label>Code de l’église</label><input name="code_eglise" placeholder="EGL12345" value={f.code_eglise} onChange={change} required/></div><div className="form-champ"><label>Téléphone</label><input name="telephone" value={f.telephone} onChange={change} placeholder="+224626483701" required/></div><div className="form-champ"><label>Email</label><input name="email" type="email" value={f.email} onChange={change}/></div><div className="form-grid"><div className="form-champ"><label>Mot de passe</label><input name="password" type="password" value={f.password} onChange={change} required/></div><div className="form-champ"><label>Confirmation</label><input name="password_confirmation" type="password" value={f.password_confirmation} onChange={change} required/></div></div>{erreur&&<p className="erreur">{erreur}</p>}<button className="btn">Créer mon compte</button><button type="button" className="btn btn-secondaire" onClick={()=>nav("/connexion")}>J’ai déjà un compte</button></form>:<form onSubmit={confirmer}><p className="sous-titre">Votre identifiant : <strong>{identifiant}</strong></p>{testMode&&<div className="credential-box" style={{marginBottom:"16px"}}><small>MODE TEST SMS — CODE DE CONFIRMATION</small><strong style={{fontSize:"2rem",letterSpacing:"0.3em"}}>{testCode}</strong><p style={{margin:0}}>Les SMS réels sont désactivés. Utilisez ce code pour terminer la création.</p></div>}<div className="form-champ"><label>Code de confirmation à 6 chiffres</label><input inputMode="numeric" autoComplete="one-time-code" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} maxLength={6} required/></div>{erreur&&<p className="erreur">{erreur}</p>}<button className="btn">Confirmer le numéro</button><button type="button" className="btn btn-secondaire" onClick={()=>nav("/connexion")}>Retour à la connexion</button></form>}</section></div>;
}
