# Generated by Django 5.0.6 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_affectation', models.CharField(choices=[('PASTEUR', "Pasteur / Responsable d'église"), ('ADMIN_LOCAL', 'Administrateur local'), ('MISSIONNAIRE', 'Missionnaire'), ('RESPONSABLE_DEPT', 'Responsable de département')], max_length=20)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('affecte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_realisees', to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='churches.eglise')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_affectation'],
            },
        ),
    ]
