# Generated by Django 5.0.6 on 2026-09-12 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_annexe_annexe_unique_annexe_nom_par_eglise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('OFFICIEL', 'Document officiel'), ('ADMINISTRATIF', 'Administratif'), ('RAPPORT', 'Rapport'), ('PROJET', 'Projet'), ('AUTRE', 'Autre')], default='OFFICIEL', max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('est_word', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('eglise_expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_envoyes', to='churches.eglise')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDestinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.BooleanField(default=False)),
                ('compte_reception', models.BooleanField(default=False)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaisons_destinataires', to='documents.document')),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_destines', to='churches.eglise')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='destinataires',
            field=models.ManyToManyField(related_name='documents_recus', through='documents.DocumentDestinataire', to='churches.eglise'),
        ),
        migrations.AddConstraint(
            model_name='documentdestinataire',
            constraint=models.UniqueConstraint(fields=('document', 'eglise'), name='unique_document_eglise_destinataire'),
        ),
    ]
