# Generated by Django 5.0.6 on 2026-09-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_courrier', models.CharField(choices=[('MISSION', 'Lettre de mission'), ('RECOMMANDATION', 'Lettre de recommandation'), ('NOTE', 'Note de service')], max_length=20)),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField(help_text='Corps du texte de la lettre (exemple à personnaliser).')),
                ('lieu_emission', models.CharField(default='Conakry', max_length=100)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='courriers/')),
                ('lu', models.BooleanField(default=False)),
                ('eglise_destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_recus', to='churches.eglise')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_envoyes', to=settings.AUTH_USER_MODEL)),
                ('membre_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_le_concernant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_emission', '-id'],
            },
        ),
    ]
