# Generated by Django 5.0.6 on 2026-09-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='cachete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courrier',
            name='fichier_word',
            field=models.FileField(blank=True, null=True, upload_to='courriers/word/'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='signe',
            field=models.BooleanField(default=False),
        ),
    ]
