# Generated by Django 5.0.6 on 2026-09-12 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0003_eglise_responsable_email_eglise_responsable_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('plateforme', models.CharField(choices=[('JITSI', 'Jitsi Meet'), ('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('AUTRE', 'Autre')], default='JITSI', max_length=20)),
                ('lien', models.URLField(max_length=500)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='churches.eglise')),
                ('organisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_organisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-date_debut'],
            },
        ),
    ]
